[package]
name = "quest15"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5.53", features = ["derive"] }
color-eyre = "0.6.5"
itertools = "0.14.0"
memoize = "0.5.1"
num-rational = "0.4.2"
pathfinding = "4.14.0"
rustc-hash = "2.1.1"
